# Generated by Django 5.1.3 on 2024-11-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('incident_type', models.CharField(max_length=50)),
                ('incident_description', models.CharField(max_length=500)),
                ('evidence', models.FileField(upload_to='uploaded_files')),
            ],
        ),
    ]
