# Generated by Django 5.1.3 on 2024-11-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='evidence',
            field=models.FileField(upload_to=''),
        ),
    ]
